name: advanced_project
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dio: ^5.9.0
  retrofit: ^4.7.2
  retrofit_generator: ^10.0.5
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  flutter_native_splash: ^2.4.6
  injectable: ^2.5.1
  injectable_generator: ^2.8.1
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/